#!/bin/bash

#sanify check

if [ $# -lt 1 ] ; then
	echo "usage $0 ROOTDIR"
	exit 1
fi

rootdir=$1
    
if [ -z "$rootdir" ]; then
	echo "ROOTDIR is not set."
	exit 1
fi
		
# Check root directory
if [ ! -d $rootdir ]; then
	echo "$rootdir: should be a directory."
	exit 1
fi

pushd $rootdir > /dev/null

# Bootstrap a minimal chroot tree for the rest installation
mkdir -p var/lib/rpm
mkdir -p var/lock/rpm
mkdir -p var/tmp
mkdir -p dev
mkdir -p etc


	touch etc/ld.so.conf
	chmod 0644 etc/ld.so.conf
	chown root.root etc/ld.so.conf
	# mount /dev/pts and proc
	echo "proc  /proc       proc    defaults    0       0" >> etc/fstab
	echo "none  /dev/pts    devpts  rw          0       0" >> etc/fstab

# add some groups and users, provides by aaa_base
# some rpms (filesystem,..) use it before aaa_base installation
echo "root:x:0:
bin:x:1:daemon
daemon:x:2:
sys:x:3:
tty:x:5:
disk:x:6:
lp:x:7:
kmem:x:9:
mail:x:12:
news:x:13:
uucp:x:14:
shadow:x:15:
dialout:x:16:
audio:x:17:
video:x:33:
games:x:40:
trusted:x:42:
users:x:100:" > etc/group


echo "root:x:0:0:root:/root:/bin/bash
lp:x:4:7:Printing daemon:/var/spool/lpd:/bin/bash
mail:x:8:12:Mailer daemon:/var/spool/clientmqueue:/bin/false
news:x:9:13:News system:/etc/news:/bin/bash
uucp:x:10:14:Unix-to-Unix CoPy system:/etc/uucp:/bin/bash
games:x:12:100:Games account:/var/games:/bin/bash
man:x:13:62:Manual pages viewer:/var/cache/man:/bin/bash
wwwrun:x:30:8:WWW daemon apache:/var/lib/wwwrun:/bin/false
nobody:x:65534:65533:nobody:/var/lib/nobody:/bin/bash" > etc/passwd

mknod dev/zero c 1 5
chmod 666 dev/zero
popd > /dev/null

#export YAST_IS_RUNNING="no"


