#!/bin/bash

MYDIR=`pwd`
cd / >/dev/null

ln -sf /proc/mounts etc/mtab

# omit syncing for all log files
CFG_FILE=etc/syslog.conf
if [ -f $CFG_FILE ]; then
    cat $CFG_FILE | sed "s,[[:blank:]]/var/log/, -/var/log/,g" > ${CFG_FILE}.$$
    if [ $? -eq 0 ]; then
        chown --reference=${CFG_FILE} $CFG_FILE.$$ || exit 1 > /dev/null 2>&1
	chmod --reference=${CFG_FILE} $CFG_FILE.$$ || exit 1 > /dev/null 2>&1
	mv -f $CFG_FILE.$$ ${CFG_FILE} > /dev/null 2>&1
    fi
fi


# Convert system to shadow password files
usr/sbin/pwconv

# do not launch getty on tty devices - they are not accessible from Container
mkdir -p etc/init.removed
mv -f etc/init/tty* etc/init.removed

# do not launch init scripts
mv -f etc/init/control-alt-delete.conf etc/init.removed
mv -f etc/init/hwclock* etc/init.removed
mv -f etc/init/mountall* etc/init.removed
mv -f etc/init/rcS.conf etc/init.removed
mv -f etc/init/portmap.conf etc/init.removed
mv -f etc/init/anacron.conf etc/init.removed
mv -f etc/init/network* etc/init.removed
mv -f etc/init/*udev* etc/init.removed
mv -f etc/init/rc-sysinit.conf etc/init.removed
mv -f etc/init/rc.conf etc/init.removed
mv -f etc/init/smbd.conf etc/init.removed
mv -f etc/init/nmbd.conf etc/init.removed
mv -f etc/init/plymouth*.conf etc/init.removed
mv -f etc/init/mounted*.conf etc/init.removed
mv -f etc/init/ssh.conf etc/init.removed

# Fix networking.conf
cat etc/init.removed/networking.conf | grep -v udevtrigger | \
sed "s,(local-filesystems,local-filesystems,g" > etc/init/networking.conf

# Fix rc-sysinit.conf
cat etc/init.removed/rc-sysinit.conf | sed "s, and net-device-up IFACE=lo,,g" | \
sed "s,^console output,#console output,g" | sed "s,^env INIT_VERBOSE,#env INIT_VERBOSE,g" \
> etc/init/rc-sysinit.conf

cat etc/init.removed/rc.conf | \
sed "s,^console output,#console output,g" | sed "s,^env INIT_VERBOSE,#env INIT_VERBOSE,g" \
> etc/init/rc.conf

# Fix ssh.conf
cat etc/init.removed/ssh.conf | \
sed "s,^oom never,#oom never,g" > etc/init/ssh.conf

# Create mountall upstart config
echo "# mountall - Mount filesystems on boot
#
# This helper mounts filesystems in the correct order as the devices
# and mountpoints become available.

description	\"Mount filesystems on boot\"

start on startup

task

emits virtual-filesystems
emits local-filesystems
emits remote-filesystems
emits all-swaps
emits all-filesystems
emits filesystem

pre-start script
    find /var/run -mindepth 1 -maxdepth 1 | grep -v utmp | xargs rm -rf
    mkdir -p /var/run/network
    find /var/lock -mindepth 1 -maxdepth 1 | xargs rm -rf
end script

post-start script
    initctl emit -n filesystem
    initctl emit -n all-swaps
    initctl emit -n all-filesystems
    initctl emit -n virtual-filesystems
    initctl emit -n remote-filesystems
    initctl emit -n local-filesystems
    mount -a
end script
" > etc/init/mountall.conf

# Create lo setup config

echo "
auto lo
iface lo inet loopback
	address 127.0.0.1
	netmask 255.0.0.0
	broadcast 127.255.255.255
	up ip route replace 127.0.0.0/8 dev lo
" > etc/network/interfaces.template


# disable all xinetd services without disable option
CFG_FILE=/etc/xinetd.conf
if [ -f $CFG_FILE ]; then
	CFG_TEMP=`mktemp $CFG_FILE.XXXXXX`
	awk -f - << 'EOF' $CFG_FILE > $CFG_TEMP 
BEGIN {
        lopen=0;
        lfound=0;
}
/^service .*/{
        print $0;
        lopen=1;
        lfound=0;
        next;
}
/^.*disable .*/{
        print $0;
        lfound=1;
        next;
}
/^\}.*/{
        if (!lfound)
                print "	disable		= yes";
        print $0;
        lopen=0;
        next;
}
{
        print $0;
}
EOF
	if [ $? -eq 0 ]; then
	        chown --reference=$CFG_FILE $CFG_TEMP || exit 1 > /dev/null 2>&1
		chmod --reference=$CFG_FILE $CFG_TEMP || exit 1 > /dev/null 2>&1
		mv -f $CFG_TEMP $CFG_FILE > /dev/null 2>&1
	fi
fi

chown -R root.root usr/share/doc/apache2-doc/manual/*

# turn off and stop some services
for i in klogd bind9 quotarpc samba fetchmail ondemand wide-dhcpv6-client; do
	usr/sbin/update-rc.d -f $i remove > /dev/null 2>&1
	etc/init.d/$i stop > /dev/null 2>&1
done

# create devices, needed to enter into Container
if [ ! -c dev/ptmx ]; then
    mknod dev/ptmx c 5 2
    chmod 666 dev/ptmx
fi

for i in 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15; do
    a=`awk -v num=$i 'BEGIN { printf("%x\n", num) }'`
    if [ ! -c dev/ttyp$i ]; then
	mknod dev/ttyp$a c 3 $i
    fi
    if [ ! -c dev/ptyp$i ]; then
	mknod dev/ptyp$a c 2 $i
    fi
done

#export PATH
CFG_FILE=etc/bash.bashrc
if [ -f $CFG_FILE ] ; then
	echo >> $CFG_FILE
	echo "export PATH" >> $CFG_FILE
	echo >> $CFG_FILE
fi


# apache tuning
CFG_FILE=etc/apache2/apache2.conf
if [ -f $CFG_FILE ]; then
    sed -e "s/^[[:blank:]]*StartServers[[:blank:]]*.*/StartServers       1/" \
	-e "s/^[[:blank:]]*MinSpareServers[[:blank:]]*.*/MinSpareServers    1/" \
	-e "s/^[[:blank:]]*MaxSpareServers[[:blank:]]*.*/MaxSpareServers    5/" \
	-e "s/^[[:blank:]]*ServerLimit[[:blank:]]*.*/ServerLimit       10/" \
	-e "s/^[[:blank:]]*MaxClients[[:blank:]]*.*/MaxClients        10/" \
	-e "s/^[[:blank:]]*MinSpareThreads[[:blank:]]*.*/MinSpareThreads    1/" \
	-e "s/^[[:blank:]]*MaxSpareThreads[[:blank:]]*.*/MaxSpareThreads    4/" \
	$CFG_FILE > ${CFG_FILE}.$$
	if [ $? -eq 0 ]; then
	        chown --reference=${CFG_FILE} $CFG_FILE.$$ || exit 1 > /dev/null 2>&1
		chmod --reference=${CFG_FILE} $CFG_FILE.$$ || exit 1 > /dev/null 2>&1
		mv -f $CFG_FILE.$$ ${CFG_FILE} > /dev/null 2>&1
        fi
fi

# and disable root user
/usr/sbin/usermod -L root

# do not execute some cron-jobs by default
rm -rf /etc/cron.d/*
rm -f `find /etc/cron.daily/ -type f | grep -v "logrotate\|sysklogd"`
rm -rf /etc/cron.weekly/*
rm -rf /etc/cron.monthly/*

# move post files from /
MAILF=d???????????????
[ -n "$MAILF" ] && rm -f $MAILF
#[ -n "$MAILF" ] && mv $MAILF var/spool/mail/
MAILF=Q???????????????
[ -n "$MAILF" ] && rm -f $MAILF
#[ -n "$MAILF" ] && mv $MAILF var/spool/mail/

# Fill /etc/apt/sources.list
if [ ! -f etc/apt/sources.list ]; then

cat << EOF > etc/apt/sources.list
deb http://archive.ubuntu.com/ubuntu lucid main restricted universe
deb http://archive.ubuntu.com/ubuntu lucid-updates main restricted universe
deb http://archive.ubuntu.com/ubuntu lucid-security main restricted universe

EOF

fi

# Turn back klogd init script
mv -f etc/init.d/klogd.dpkg-dist etc/init.d/klogd

# Clean /var/run

rm -rf var/run/*

# Create utmp

cat /dev/null > var/run/utmp
chmod 0664 var/run/utmp
chown root.utmp var/run/utmp

# Clean logs

for i in `find var/log/ -type f`; do
    echo "" > $i
done

# Remove /dev/log
rm -f dev/log >/dev/null 2>&1

# Copy devices
cp -af dev/* lib/udev/devices >/dev/null 2>&1

# ssh host keys hack

echo "#!/bin/sh
rm -f etc/ssh/ssh_host_*
/usr/bin/ssh-keygen -t rsa -N '' -f /etc/ssh/ssh_host_rsa_key
/usr/bin/ssh-keygen -t dsa -N '' -f /etc/ssh/ssh_host_dsa_key
/usr/bin/ssh-keygen -t rsa1 -N '' -f /etc/ssh/ssh_host_key
/usr/sbin/service ssh restart
rm -f /etc/init.d/ssh_key_hack.sh
rm -f /etc/rc2.d/S11sshhack
" > etc/init.d/ssh_key_hack.sh
chmod a+x etc/init.d/ssh_key_hack.sh
ln -s /etc/init.d/ssh_key_hack.sh etc/rc2.d/S11sshhack

# Fix modprobe.conf
touch etc/modprobe.conf

# Fix modules.dep
echo "#! /bin/sh
### BEGIN INIT INFO
# Provides:          modules_dep
# Required-Start:
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 6
# Short-Description: modules.dep creation.
# Description:       Create and destroy modules.dep.
### END INIT INFO

case \"\$1\" in
  start|\"\")
	if [ ! -d \"/lib/modules/\`uname -r\`\" ]; then
		mkdir /lib/modules/\`uname -r\`
	fi
	depmod -a >/dev/null 2>&1
	;;
  restart|reload|force-reload)
	echo \"Error: argument '\$1' not supported\" >&2
	exit 3
	;;
  stop)
	if [ -d \"/lib/modules/\`uname -r\`\" ]; then
		rm -rf /lib/modules/\`uname -r\`
	fi
	;;
  *)
	echo \"Usage: modules_dep.sh [start|stop]\" >&2
	exit 3
	;;
esac

:

" > etc/init.d/modules_dep.sh
chmod a+x etc/init.d/modules_dep.sh
/usr/sbin/update-rc.d modules_dep.sh defaults >/dev/null 2>&1

# Create empty /etc/inittab file
touch etc/inittab

# Turn back wide-dhcpv6-client init script and clean default conf file
# regenerate dhcp6cctlkey if exists
mv -f etc/init.d/wide-dhcpv6-client.dpkg-dist etc/init.d/wide-dhcpv6-client
cat > etc/default/wide-dhcpv6-client <<'EOFINITCONFFILE'
# Defaults for dhcpv6 client initscript
# Used by /etc/init.d/wide-dhcpv6-client

# Interfaces on which the client should send DHCPv6 requests and listen to
# answers. If empty, the client is deactivated.
INTERFACES=""
EOFINITCONFFILE

rm -f etc/wide-dhcpv6/dhcp6cctlkey

echo "#!/bin/sh
DHCP6CCTLKEY=/etc/wide-dhcpv6/dhcp6cctlkey

# The key mustn\'t be world readable
umask 066

echo \"Generating \${DHCP6CCTLKEY}...\" >&2
dd if=/dev/random bs=32 count=1 2>/dev/null | \
	uuencode -m \${DHCP6CCTLKEY} | \
	head -n 2 | tail -n 1 > \${DHCP6CCTLKEY}

umask 022
rm -f /etc/init.d/dhcpv6_hack.sh
rm -f /etc/rc2.d/S11dhcpv6hack
"> etc/init.d/dhcpv6_hack.sh
chmod a+x etc/init.d/dhcpv6_hack.sh
ln -s /etc/init.d/dhcpv6_hack.sh etc/rc2.d/S11dhcpv6hack

cd $MYDIR > /dev/null
