#!/bin/bash

pushd /

# Convert system to shadow password files
/usr/sbin/pwconv

# Disable root login
echo -e ",s/^root::/root:!:/\nwq" | ed -s /etc/shadow

# turn services off
# 'nfslock' is not included
list="anacron portmap random netfs rawdevices"
for i in $list; do
	/sbin/chkconfig --level 3 $i off
done

# turn off remote user identification
for xf in /etc/xinetd.d/popa3d /etc/xinetd.d/popa3ds; do
	[ -r $xf ] && \
		fgrep -v USERID $xf > $xf.$$ && mv $xf.$$ $xf
done

# turn services on
list="httpd iptables popa3d popa3ds xinetd"
for i in $list; do
	/sbin/chkconfig --level 3 $i on	
done

# do not launch mingetty on tty devices - they are not accessible from VE
CFG_FILE=/etc/inittab
if [ -f $CFG_FILE ]; then
	CFG_TEMP=`mktemp $CFG_FILE.XXXXXX`
	sed '/^.*mingetty.*$/d' $CFG_FILE > $CFG_TEMP && \
	mv -f $CFG_TEMP $CFG_FILE && chmod 644 $CFG_FILE
fi

# disable klogd
sed -e 's/daemon klogd/passed klogd skipped #&/' \
	-e 's/killproc klogd/passed klogd skipped#&/' \
	< /etc/init.d/syslog > /etc/init.d/syslog.tmp \
	&& mv /etc/init.d/syslog.tmp /etc/init.d/syslog 
rm -f /etc/init.d/syslog.tmp
chmod 755 /etc/init.d/syslog

cat /etc/sysctl.conf | grep "^kernel" >/dev/null 2>&1
if [ $? -eq 0 ]; then
	mv -f /etc/sysctl.conf /etc/sysctl.conf-pre-kernel
	cat /etc/sysctl.conf-pre-kernel | \
		sed "s,^kernel.sysrq,# kernel.sysrq,g" | \
		sed "s,^kernel.core_uses_pid,# kernel.core_uses_pid,g" > \
		/etc/sysctl.conf
	[ $? -eq 0 ] || mv -f /etc/sysctl.conf-pre-kernel /etc/sysctl.conf
fi

# do not execute some cron-jobs by default
chmod a-x /etc/cron.daily/rpm /etc/cron.daily/slocate.cron \
	/etc/cron.daily/makewhatis.cron /etc/cron.weekly/makewhatis.cron

# mount /dev/pts
echo "none	/dev/pts	devpts	rw	0	0" >> /etc/fstab

# Fix /etc/syslog.conf
echo -e ',s^\([[:space:]]\)\(/var/log/\)^\\1-\\2^\nwq' | ed -s /etc/syslog.conf

# Rebuild rpm database
rpm --rebuilddb


