#!/bin/bash

rpm -e --justdb --allmatches libselinux --nodeps > /dev/null 2>&1
rpm -e --justdb elfutils.i386 e2fsprogs.i386 --nodeps > /dev/null 2>&1
rpm -e --justdb openjade.i386 openjade.x86_64 --nodeps > /dev/null 2>&1
rpm -e --justdb device-mapper --nodeps > /dev/null 2>&1
rpm -e --justdb caching-nameserver --nodeps > /dev/null 2>&1
rpm -e --justdb udev hotplug --nodeps > /dev/null 2>&1
rpm -e --justdb kudzu --nodeps > /dev/null 2>&1
rpm -e --justdb lm_sensors --nodeps > /dev/null 2>&1
rpm -e --justdb iputils --nodeps > /dev/null 2>&1
rpm -e --justdb glib2.i386 glib2.x86_64 --nodeps > /dev/null 2>&1
rpm -e --justdb ncurses.i386 ncurses.x86_64 --nodeps  > /dev/null 2>&1
rpm -e --justdb hesiod --nodeps  > /dev/null 2>&1
rpm -e --justdb caching-nameserver --allmatches --nodeps > /dev/null 2>&1
rpm -e --justdb php-pear --nodeps > /dev/null 2>&1
rpm -e --justdb java-1.4.2-gcj-compat-devel --allmatches --nodeps > /dev/null 2>&1

:
